### PR TITLE
Use semver in flexi interdependencies

### PR DESCRIPTION
**Pull request by kybishop**
[Rendered](https://github.com/html-next/rfcs/blob/use-semver-in-flexi-interdependencies/text/use-semver-in-flexi-interdependencies.md)

### CODE REVIEW

**Comment by RobbieTheWagner** [comment]
@kybishop I feel like this will get very messy to maintain. We would need to ensure we handle every single version combination and warn about mismatches. I'm not opposed to it, just would like to make sure it is realistic.

**Comment by kybishop** [comment]
@rwwagner90 the list of semver checks would grow with each release that necessitates a new check, and should only consist of extremely straightforward checks. The only case I can envision where things are a little tricky is a three-way dependency breakage, which I believe will be very rare, and is still easy to implement.

We should _never_ have semver-spaghetti; checks should always look toward the future without cherry-picking past releases. Pseudo-code below of how these checks will look:

```javascript
// Two-way interdependent release
if (flexiDslVersion >= '2.5') {
  if (flexiDefaultStylesVersion < '2.3') {
    console.warn('Danger Will Robinson!');
  }
}

// three-way interdependent release
if (flexiDefaultStylesVersion >= '2.5'
    || flexiDslVersion >= '2.9'
    || flexiLayoutsVersion >= '2.10') {
  if (flexiDefaultStylesVersion < '2.5'
      || flexiDslVersion < '2.10'
      || flexiLayoutsVersion < '2.10') {
    console.warn('Danger Will Robinson!');
  }
}

// Another two-way interdependent release
if (flexiDslVersion >= '3.1') {
  if (flexiLayoutsVersion < '2.9') {
    console.warn('Danger Will Robinson!');
  }
}
```

EDIT: The above pseudo-code is very close to what the actual code will look like, just omitting some things for brevity.

**Comment by kybishop** [comment]
@rwwagner90 furthermore, we can periodically clean the closet with a major release of flexi across the board, wiping all semver checks besides `if (addons < '3.0') { warn }`

**Comment by RobbieTheWagner** [comment]
@kybishop sounds good to me. I'm game for giving it a go 👍. Cool with you @runspired?

**Comment by kybishop** [comment]
Chris gave a thumbs up in Slack. Merging!

**Pull request merged**
